# Buildtime Trend general settings
buildtimetrend:
    allowed_repo:
      - "buildtimetrend"
      - "ruleant"
    loglevel: "DEBUG"
    data_detail: "full"
    repo_data_detail:
      "buildtimetrend/service": "basic"
