# Buildtime Trend general settings
buildtimetrend:
    denied_repo:
      - "deny_this_substring"
      - "my_name/repo_name"
    allowed_repo:
      - "allow_this_substring"
      - "my_name/repo_name"
    travis_account_token: "Travis CI account token of user who set up the repo"
    loglevel: "WARNING" # possible values : "DEBUG", "INFO", "WARNING", "ERROR"

# Keen.io connection settings
keen:
    project_id: "Keen.io project_id"
    write_key: "Keen.io write_key"
    read_key: "Keen.io read_key"
