---
- name: Add init.d {{service_name}} daemon script
  template: src=init.d-template.j2 dest=/etc/init.d/{{service_name}} mode=0755
  notify:
    - start the {{service_name}} daemon

- name: Start {{service_name}} daemon on boot
  service: name={{service_name}} enabled=yes
